agents:
  coordinator:
    prompt: coordinator
    tools:
      - handoff
    output:
      schema: null
    batch_enabled: false
    max_concurrency: 2
    is_default: true

  preface_agent:
    prompt: preface_agent
    tools:
      - update_section
    output:
      schema: 01-preface.json
    dynamic: false
    batch_enabled: false

  getting_started_agent:
    prompt: getting_started_agent
    tools:
      - update_section
    output:
      schema: 02-getting-started.json
    dynamic: false
    batch_enabled: false

  features_agent:
    prompt: features_agent
    tools:
      - update_section
    output:
      schema: 03-01-list-of-features.json
    dynamic: false
    batch_enabled: false

  entity_agent:
    prompt: entity_agent
    tools:
      - create_entity
      - list_entities
      - delete_entity
    output:
      schema: 05-entity.json
    dynamic: false
    batch_enabled: false
